---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ctf-prod
  name: app-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-proxy
  template:
    metadata:
      labels:
        app: app-proxy
    spec:
      containers:
      - name: nginx
        image: us-central1-docker.pkg.dev/middesk-ctf-2023/ctf-bot/proxy:v0.4
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 512Mi
            cpu: 500m
          limits:
            memory: 1024Mi
            cpu: 1000m
---
apiVersion: v1
kind: Service
metadata:
  namespace: ctf-prod
  name: app-proxy
spec:
  selector:
    app: app-proxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: ctf-prod
  name: app-proxy-elb
spec:
  tls:
  - hosts:
    - "*.ctf.middesk.com"
    secretName: wildcard-ctf-middesk-com
  defaultBackend:
    service:
      name: app-proxy
      port:
        number: 80
