---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: level-provisioner
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: level-provisioner
subjects:
  - kind: ServiceAccount
    name: level-provisioner
    namespace: default
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: cloud-functions-token
  namespace: default
  annotations:
    kubernetes.io/service-account.name: level-provisioner
